-- MySQL Script generated by MySQL Workbench
-- Tue May 23 04:12:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UVEats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UVEats` ;

-- -----------------------------------------------------
-- Schema UVEats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UVEats` DEFAULT CHARACTER SET utf8 ;
USE `UVEats` ;

-- -----------------------------------------------------
-- Table `UVEats`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `tipo` VARCHAR(45) NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVEats`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVEats`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`Productos` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `precio` DECIMAL(6,2) NULL,
  `idCategoria` INT NULL,
  `estadoProducto` VARCHAR(45) NULL,
  `fotoProducto` LONGBLOB NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `UVEats`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCategoria_idx` ON `UVEats`.`Productos` (`idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `UVEats`.`Resenas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`Resenas` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`Resenas` (
  `idResena` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NULL,
  `idUsuario` INT NULL,
  `resena` VARCHAR(500) NULL,
  PRIMARY KEY (`idResena`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `UVEats`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `UVEats`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idUsuario_idx` ON `UVEats`.`Resenas` (`idUsuario` ASC) VISIBLE;

CREATE INDEX `idProducto_idx` ON `UVEats`.`Resenas` (`idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `UVEats`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(6,2) NULL,
  `EstadoPedido` VARCHAR(45) NULL,
  `idUsuario` INT NULL,
  `fechaPedido` DATE NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `idUsuarioPedido`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `UVEats`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idUsuario_idx` ON `UVEats`.`Pedidos` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `UVEats`.`ProductosPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`ProductosPedido` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`ProductosPedido` (
  `idProductoPedido` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NULL,
  `idProducto` INT NULL,
  `Cantidad` INT NULL,
  `Subtotal` DECIMAL(6,2) NULL,
  `estadoProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductoPedido`),
  CONSTRAINT `idPedidoProducto`
    FOREIGN KEY (`idPedido`)
    REFERENCES `UVEats`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductoPedido`
    FOREIGN KEY (`idProducto`)
    REFERENCES `UVEats`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idPedido_idx` ON `UVEats`.`ProductosPedido` (`idPedido` ASC) VISIBLE;

CREATE INDEX `idProducto_idx` ON `UVEats`.`ProductosPedido` (`idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `UVEats`.`ConversacionesPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVEats`.`ConversacionesPedido` ;

CREATE TABLE IF NOT EXISTS `UVEats`.`ConversacionesPedido` (
  `idConversacionesPedido` INT NOT NULL,
  `idPedido` INT NULL,
  `conversacion` LONGTEXT NULL,
  PRIMARY KEY (`idConversacionesPedido`),
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `UVEats`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idPedido_idx` ON `UVEats`.`ConversacionesPedido` (`idPedido` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
